local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

function AtlasLoot:InitializeMenuData()
    local menu = self.ui.menus.data

    menu["ZulGurub"] = {
        Module = "AtlasLoot_OriginalWoW",
        Name = "Zul'Gurub",
        Type = "ClassicRaid",
        Map = "ZulGurub",
        { "High Priestess Jeklik", 14517 },
        { "High Priest Venoxis", 14507 },
        { "High Priestess Mar'li", 14510 },
        { "Bloodlord Mandokir", 11382 },
        { "Gahz'ranka", 15114 },
        { "High Priest Thekal", 14509 },
        { "High Priestess Arlokk", 14515 },
        { "Jin'do the Hexxer", 11380 },
        { "Hakkar", 14834 },
    }

    menu["Naxxramas60"] = {
	Module = "AtlasLoot_OriginalWoW",
	Name = "Naxxramas",
	Type = "ClassicRaid",
	Map = "Naxxramas60",
		{ "Patchwerk", 16028 },
		{ "Grobbulus", 15931 },
		{ "Gluth", 15932 },
		{ "Thaddius", 15928 },
		{ "Anub'Rekhan", 15956 },
		{ "Grand Widow Faerlina",  },
		{ "Maexxna", 15953 },
		{ "Instructor Razuvious", 15952 },
		{ "Gothik the Harvester", 16061 },
		{ "The Four Horsemen", 16060 },
		{ "Noth the Plaguebringer", 15954 },
		{ "Heigan the Unclean", 15936 },
		{ "Loatheb", 16011 },
		{ "Sapphiron", 15989 },
		{ "Kel'Thuzad", 15990 },

    }

	menu["RuinsofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ruins of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheRuinsofAhnQiraj",
		{ "Kurinnaxx", 15348 },
		{ "General Rajaxx", 15341 },
		{ "Moam", 15340 },
		{ "Buru the Gorger", 15370 },
		{ "Ayamiss the Hunter", 15369 },
		{ "Ossirian the Unscarred", 15339 },
		{ "Trash Mobs" },
		{ "AQ Enchants" },
	}

	menu["TempleofAQ"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Temple of Ahn'Qiraj",
		Type = "ClassicRaid",
		Map = "TheTempleofAhnQiraj",
		{ "The Prophet Skeram", 15263 },
		{ "The Bug Family" },
		{ "Battleguard Sartura", 15516 },
		{ "Fankriss the Unyielding", 15510 },
		{ "Viscidus", 15299 },
		{ "Princess Huhuran", 15509 },
		{ "The Twin Emperors", 15275 },
		{ "Ouro", 15517 },
		{ "C'Thun", 15727 },
		{ "Trash Mobs" },
		{ "Shoulder Enchants" },
		{ "Trash Mobs" },
	}

	menu["AQOpening"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "AQOpening",
		{ "AQOpening" },
	}

	menu["BlackfathomDeeps"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackfathom Deeps",
		Type = "ClassicDungeon",
		Map = "BlackfathomDeeps",
		{ "Ghamoo-ra", 4887 },
		{ "Lady Sarevess", 4831 },
		{ "Gelihast", 6243 },
		{ "Baron Aquanis", 12876 },
		{ "Twilight Lord Kelris", 4832 },
		{ "Old Serra'kis", 4830 },
		{ "Aku'mai", 4829 },
		{ "Trash Mobs" },
	}

	menu["BlackrockDepths"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Depths",
		Type = "ClassicDungeonExt",
		Map = "BlackrockDepths",
		{ "Overmaster Pyron" },
		{ "Lord Roccor", 9025 },
		{ "High Interrogator Gerstahn", 9018 },
		{ "Ring of Law" },
		{ "Theldren" },
		{ "Houndmaster Grebmar", 9319 },
		{ "Monument of Franclorn Forgewright" },
		{ "Pyromancer Loregrain", 9024 },
		{ "The Vault" },
		{ "Warder Stilgiss", 9041 },
		{ "Verek", 9042 },
		{ "Fineous Darkvire", 9056 },
		{ "Lord Incendius", 9017 },
		{ "Bael'Gar", 9016 },
		{ "General Angerforge", 9033 },
		{ "Golem Lord Argelmach", 8983 },
		{ "Hurley Blackbreath", 9537 },
		{ "Phalanx", 9502 },
		{ "Ribbly Screwspigot" },
		{ "Plugger Spazzring" },
		{ "Ambassador Flamelash", 9156 },
		{ "Panzor the Invincible (Rare)" },
		{ "Summoner's Tomb" },
		{ "Shadowforge Flame Keeper" },
		{ "Magmus", 9938 },
		{ "Emperor Dagran Thaurissan", 8929 },
		{ "Princess Moira Bronzebeard" },
		{ "Blacksmith Plans" },
		{ "Trash Mobs" },
	}

	menu["BlackrockCaverns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackrock Caverns",
		Type = "ClassicDungeonExt",
		{ "Ascendant Lord Obsidius", 39705 },
		{ "Beauty", 39700 },
		{ "Corla, Herald of Twilight", 39679 },
		{ "Karsh Steelbender <Twilight Armorer>", 39698 },
		{ "Rom'ogg Bonecrusher", 39665 },
	}

	menu["LowerBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Lower Blackrock Spire",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "BlackrockSpire",
		{ "Scarshield Quartermaster" },
		{ "Quest Item" },
		{ "Spirestone Butcher (Rare)" },
		{ "Highlord Omokk", 9196 },
		{ "Spirestone Battle Lord (Rare)" },
		{ "Spirestone Lord Magus (Rare)" },
		{ "Shadow Hunter Vosh'gajin", 9236 },
		{ "War Master Voone", 9237 },
		{ "Mor Grayhoof (Summon)", 16080 },
		{ "Bannok Grimaxe (Rare)" },
		{ "Mother Smolderweb", 10596 },
		{ "Crystal Fang", 10376 },
		{ "Urok Doomhowl (Summon)" },
		{ "Quartermaster Zigris", 9736 },
		{ "Gizrul the Slavener", 10268 },
		{ "Halycon", 10220 },
		{ "Ghok Bashguud (Rare)" },
		{ "Overlord Wyrmthalak", 9568 },
		{ "Burning Felguard (Rare, Random)" },
		{ "Trash Mobs" },
	}

	menu["UpperBlackrock"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Upper Blackrock Spire",
		Type = "ClassicDungeonExt",
		Map = "BlackrockSpire",
		{ "Pyroguard Emberseer" },
		{ "Solakar Flamewreath" },
		{ "Father Flame" },
		{ "Quest Item" },
		{ "Jed Runewatcher" },
		{ "Goraluk Anvilcrack", 10899 },
		{ "Warchief Rend Blackhand", 10429 },
		{ "Gyth" },
		{ "The Beast", 10430 },
		{ "Lord Valthalak (Summon)" },
		{ "General Drakkisath", 10363 },
		{ "Trash Mobs" },
	}

	menu["MoltenCore"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Molten Core",
		Type = "ClassicRaid",
		Map = "MoltenCore",
		{ "Lucifron", 12056 },
		{ "Magmadar", 11982 },
		{ "Gehennas", 12259 },
		{ "Garr", 12057 },
		{ "Shazzrah", 12264 },
		{ "Baron Geddon", 12056 },
		{ "Golemagg the Incinerator", 11988 },
		{ "Sulfuron Harbinger", 12098 },
		{ "Majordomo Executus", 12018 },
		{ "Ragnaros", 11502 },
		{ "Random Boss Drops" },
		{ "Trash Mobs" },
	}

	menu["BlackwingLair"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Blackwing Lair",
		Type = "ClassicRaid",
		Map = "BlackwingLair",
		{ "Razorgore the Untamed", 12435 },
		{ "Vaelastrasz the Corrupt", 13020 },
		{ "Broodlord Lashlayer", 12017 },
		{ "Firemaw", 11983 },
		{ "Ebonroc", 34036 },
		{ "Flamegor", 34037 },
		{ "Chromaggus", 14020 },
		{ "Nefarian", 11583 },
		{ "Trash Mobs" },
	}

	menu["DireMaulEast"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul East",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		{ "Pusillin" },
		{ "Zevrim Thornhoof", 11490 },
		{ "Lethtendris", 14327 },
		{ "Pimgib" },
		{ "Hydrospawn", 13280 },
		{ "Alzzin the Wildshaper", 11492 },
		{ "Isalien" },
		{ "Trash Mobs" },
		{ "Dire Maul Books" },
	}

	menu["DireMaulNorth"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul North",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		{ "Guard Mol'dar", 14326 },
		{ "Stomper Kreeg", 14322 },
		{ "Guard Fengus", 14321 },
		{ "Knot Thimblejack" },
		{ "Guard Slip'kik", 14323 },
		{ "Captain Kromcrush", 14325 },
		{ "Cho'Rush the Observer", 14324 },
		{ "King Gordok", 11501 },
		{ "DM North Tribute Chest" },
	}

	menu["DireMaulWest"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dire Maul West",
		Type = "ClassicDungeonExt",
		Map = "DireMaul",
		{ "Tendris Warpwood", 11489 },
		{ "Illyanna Ravenoak", 11488 },
		{ "Magister Kalendris", 11487 },
		{ "Tsu'zee", 11467 },
		{ "Immol'thar", 11496 },
		{ "Lord Hel'nurath", 14506 },
		{ "Prince Tortheldrin", 11486 },
		{ "Shen'dralar Provisioner" },
		{ "Trash Mobs" },
	}

	menu["Gnomeregan"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Gnomeregan",
		Type = "ClassicDungeon",
		Map = "Gnomeregan",
		{ "Namdo Bizzfizzle" },
		{ "Techbot", 6231 },
		{ "Grubbis", 7361 },
		{ "Viscous Fallout", 7079 },
		{ "Electrocutioner 6000", 6235 },
		{ "Crowd Pummeler 9-60", 6229 },
		{ "Dark Iron Ambassador", 6228 },
		{ "Mekgineer Thermaplugg", 7800 },
		{ "Trash Mobs" },
	}

	menu["KarazhanCrypts"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Karazhan Crypts",
		Type = "ClassicDungeonExt",
		{ "Cynfael", 254401 },
		{ "Dryn Miel <The Second Eidolon>", 254413 },
		{ "Kurgoth Doomreaver", 254406 },
		{ "The Judgement of Sinners", 254405 },
		{ "Captain Taveir (Rare Spawn)", 254495 },
		{ "Kelivex Autumnvale (Rare Spawn)", 254493 },
	}

	menu["Maraudon"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Maraudon",
		Type = "ClassicDungeon",
		Map = "Maraudon",
		{ "Noxxion" },
		{ "Razorlash" },
		{ "Lord Vyletongue" },
		{ "Meshlok the Harvester" },
		{ "Celebras the Cursed" },
		{ "Landslide" },
		{ "Tinkerer Gizlock" },
		{ "Rotgrip" },
		{ "Princess Theradras", 35009 },
		{ "Quest Item" },
	}

	menu["RagefireChasm"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Ragefire Chasm",
		Type = "ClassicDungeon",
		Map = "RagefireChasm",
		{ "Taragaman the Hungerer", 11520 },
		{ "Zelemar the Wrathful", 17830 },
		{ "Jergosh the Invoker", 11518 },
		{ "Oggleflint" },
	}

	menu["RazorfenDowns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Downs",
		Type = "ClassicDungeon",
		Map = "RazorfenDowns",
		{ "Tuten'kash" },
		{ "Henry Stern" },
		{ "Mordresh Fire Eye" },
		{ "Glutton" },
		{ "Ragglesnout" },
		{ "Lady Falther'ess" },
		{ "Amnennar the Coldbringer" },
		{ "Plaguemaw the Rotting" },
		{ "Trash Mobs" },
	}

	menu["RazorfenKraul"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Razorfen Kraul",
		Type = "ClassicDungeon",
		Map = "RazorfenKraul",
		{ "Roogug", 6168 },
		{ "Aggem Thorncurse", 4424 },
		{ "Death Speaker Jargba", 4428 },
		{ "Razorfen Spearhide" },
		{ "Overlord Ramtusk", 4420 },
		{ "Agathelos the Raging", 4422 },
		{ "Blind Hunter", 4425 },
		{ "Charlga Razorflank", 4421 },
		{ "Earthcaller Halmgar", 4842 },
		{ "Trash Mobs" },
	}

	menu["ScarletMonastery"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scarlet Monastery",
		Type = "ClassicDungeon",
		Map = "ScarletMonastery",
		{ "Armory" },
		{ "Cathedral - High Inquisitor Fairbanks" },
		{ "Scarlet Commander Mograine" },
		{ "High Inquisitor Whitemane" },
		{ "Graveyard - Interrogator Vishas" },
		{ "Bloodmage Thalnos" },
		{ "Ironspine" },
		{ "Azshir the Sleepless" },
		{ "Fallen Champion" },
		{ "Library - Houndmaster Loksey" },
		{ "Arcanist Doan" },
		{ "Trash Mobs" },
	}

	menu["Scholomance"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Scholomance",
		Type = "ClassicDungeonExt",
		Loadfirst = 3,
		Map = "Scholomance",
		{ "Quest Item" },
		{ "Blood Steward of Kirtonos", 12501 },
		{ "Kirtonos the Herald" },
		{ "Jandice Barov", 10503 },
		{ "Rattlegore", 11622 },
		{ "Death Knight Darkreaver" },
		{ "Vectus", 10432 },
		{ "Marduk Blackpool" },
		{ "Ras Frostwhisper", 10508 },
		{ "Kormok" },
		{ "Instructor Malicia", 10505 },
		{ "Doctor Theolen Krastinov", 11261 },
		{ "Lorekeeper Polkelt", 10901 },
		{ "The Ravenian", 10507 },
		{ "Lord Alexei Barov", 10504 },
		{ "Lady Illucia Barov", 10502 },
		{ "Darkmaster Gandling" },
		{ "Trash Mobs" },
	}

	menu["ShadowfangKeep"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Shadowfang Keep",
		Type = "ClassicDungeon",
		Map = "ShadowfangKeep",
		{ "Apothecary Hummel", 36296 },
		{ "Deathsworn Captain" },
		{ "Rethilgore", 3914 },
		{ "Felsteed" },
		{ "Razorclaw the Butcher", 3886 },
		{ "Baron Silverlaine", 3887 },
		{ "Commander Springvale", 4278 },
		{ "Odo the Blindwatcher", 4279 },
		{ "Fenrus the Devourer", 4274 },
		{ "Arugal's Voidwalker" },
		{ "Wolf Master Nandos", 3927 },
		{ "Archmage Arugal", 4275 },
		{ "Trash Mobs" },
	}

	menu["Stratholme"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Stratholme",
		Type = "ClassicDungeonExt",
		Map = "Stratholme",
		{ "Skul", 10393 },
		{ "Mailbox Keys" },
		{ "Fras Siabi" },
		{ "Atiesh <Hand of Sargeras>" },
		{ "Hearthsinger Forresten", 10558 },
		{ "The Unforgiven", 10516 },
		{ "Timmy the Cruel" },
		{ "Malor's Strongbox" },
		{ "Crimson Hammersmith (Summon)" },
		{ "Plans: Serenity" },
		{ "Cannon Master Willey", 10997 },
		{ "Archivist Galford", 10811 },
		{ "Balnazzar" },
		{ "Sothos and Jarien" },
		{ "Stonespine", 10809 },
		{ "Baroness Anastari", 10436 },
		{ "Black Guard Swordsmith (Summon)" },
		{ "Plans: Corruption" },
		{ "Nerub'enkan", 10437 },
		{ "Maleki the Pallid", 10438 },
		{ "Magistrate Barthilas", 10435 },
		{ "Ramstein the Gorger" },
		{ "Baron Rivendare", 10440 },
		{ "Trash Mobs" },
	}

	menu["TheDeadmines"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Deadmines",
		Type = "ClassicDungeon",
		Map = "TheDeadmines",
		{ "Marisa du'Paige" },
		{ "Brainwashed Noble" },
		{ "Foreman Thistlenettle" },
		{ "Rhahk'Zor", 644 },
		{ "Miner Johnson", 3586 },
		{ "Sneed's Shredder", 642 },
		{ "Sneed" },
		{ "Gilnid", 1763 },
		{ "Captain Greenskin", 647 },
		{ "Mr. Smite", 646 },
		{ "Cookie", 645 },
		{ "Edwin VanCleef", 639 },
	}

	menu["TheStockade"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "The Stockade",
		Type = "ClassicDungeon",
		Map = "TheStockade",
		{ "Targorr the Dread", 1696 },
		{ "Kam Deepfury", 1666 },
		{ "Bazil Thredd", 1716 },
		{ "Hamhock", 1717 },
		{ "Dextren Ward", 1663 },
		{ "Bruegal Ironknuckle", 1720 },
		{ "Quest Item's" },
	}

	menu["SunkenTemple"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Sunken Temple",
		Type = "ClassicDungeon",
		Map = "TheSunkenTemple",
		{ "Spawn of Hakkar", 24028 },
		{ "Troll Minibosses" },
		{ "Atal'alarion" },
		{ "Dreamscythe", 35011 },
		{ "Weaver" },
		{ "Avatar of Hakkar", 35012 },
		{ "Jammal'an the Prophet" },
		{ "Ogom the Wretched" },
		{ "Morphaz" },
		{ "Hazzas" },
		{ "Shade of Eranikus", 5709 },
		{ "Trash Mobs" },
	}

	menu["Uldaman"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Uldaman",
		Type = "ClassicDungeon",
		Map = "Uldaman",
		{ "Magregan Deepshadow" },
		{ "Tablet of Ryun'eh" },
		{ "Krom Stoutarm's Chest" },
		{ "Garrett Family Chest" },
		{ "Digmaster Shovelphlange" },
		{ "Baelog" },
		{ "Revelosh" },
		{ "Ironaya" },
		{ "Obsidian Sentinel" },
		{ "Ancient Stone Keeper" },
		{ "Galgann Firehammer" },
		{ "Tablet of Will" },
		{ "Shadowforge Cache" },
		{ "Grimlok" },
		{ "Archaedas" },
		{ "Trash Mobs" },
	}

	menu["WailingCaverns"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Wailing Caverns",
		Type = "ClassicDungeon",
		Map = "WailingCaverns",
		{ "Kalldan Felmoon" },
		{ "Mad Magglish" },
		{ "Trigore the Lasher" },
		{ "Boahn" },
		{ "Lord Cobrahn", 3669 },
		{ "Lady Anacondra", 3671 },
		{ "Kresh", 3653 },
		{ "Lord Pythas", 3670 },
		{ "Skum", 3674 },
		{ "Lord Serpentis", 3673 },
		{ "Verdan the Everliving", 5775 },
		{ "Mutanus the Devourer", 3654 },
		{ "Deviate Faerie Dragon" },
	}

	menu["ZulFarrak"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Zul'Farrak",
		Type = "ClassicDungeon",
		Map = "ZulFarrak",
		{ "Antu'sul" },
		{ "Theka the Martyr", 24046 },
		{ "Witch Doctor Zum'rah" },
		{ "Nekrum Gutchewer", 24081 },
		{ "Shadowpriest Sezz'ziz" },
		{ "Dustwraith" },
		{ "Sergeant Bly", 24040 },
		{ "Sandfury Executioner" },
		{ "Hydromancer Velratha", 24081 },
		{ "Gahz'rilla" },
		{ "Chief Ukorz Sandscalp" },
		{ "Zerillis", 24081 },
		{ "Trash Mobs" },
	}

	menu["Naxxramas60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Naxxramas",
		Type = "ClassicRaid",
		Map = "Naxxramas60",
		{ "Patchwerk", 16028 },
		{ "Grobbulus", 15931 },
		{ "Gluth", 15932 },
		{ "Thaddius", 15928 },
		{ "Anub'Rekhan", 15956 },
		{ "Grand Widow Faerlina", 15953 },
		{ "Maexxna", 15952 },
		{ "Instructor Razuvious", 16061 },
		{ "Gothik the Harvester", 16060 },
		{ "The Four Horsemen" },
		{ "Noth the Plaguebringer", 15954 },
		{ "Heigan the Unclean", 15936 },
		{ "Loatheb", 16011 },
		{ "Sapphiron", 15989 },
		{ "Kel'Thuzad", 15990 },
		{ "Shared Frost Resistance Gear" },
		{ "Trash Mobs" },
	}

	menu["Onyxia60"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Onyxia's Lair",
		Type = "ClassicRaid",
		Map = "Onyxia60",
		{ "Onyxia's Lair", 10184 },
	}

	menu["AuchCrypts"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun" .. ": " .. "Auchenai Crypts",
		DisplayName = "Auchenai Crypts",
		Type = "BCDungeon",
		Map = "AuchAuchenaiCrypts",
		{ "Shirrak the Dead Watcher", 18371 },
		{ "Exarch Maladaar", 18373 },
		{ "Avatar of the Martyred" },
	}

	menu["AuchManaTombs"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun" .. ": " .. "Mana-Tombs",
		DisplayName = "Mana-Tombs",
		Type = "BCDungeon",
		Map = "AuchManaTombs",
		{ "Pandemonius", 40110 },
		{ "Tavarok", 40112 },
		{ "Nexus-Prince Shaffar", 40115 },
		{ "Yor" .. " (" .. "Heroic" .. ")", 22930 },
	}

	menu["AuchSethekk"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun" .. ": " .. "Sethekk Halls",
		DisplayName = "Sethekk Halls",
		Type = "BCDungeon",
		Map = "AuchSethekkHalls",
		{ "Darkweaver Syth", 40130 },
		{ "Anzu" .. " (" .. "Heroic" .. ")", 23035 },
		{ "Talon King Ikiss", 25006 },
		{ "Trash Mobs" },
	}

	menu["AuchShadowLab"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun" .. ": " .. "Shadow Labyrinth",
		DisplayName = "Shadow Labyrinth",
		Type = "BCDungeon",
		Map = "AuchShadowLabyrinth",
		{ "Ambassador Hellmaw", 40140 },
		{ "Blackheart the Inciter", 40141 },
		{ "Grandmaster Vorpil", 40142 },
		{ "Murmur", 40143 },
		{ "Trash Mobs" },
	}

	menu["BlackTemple"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Black Temple",
		Type = "BCRaid",
		Map = "BlackTemple",
		{ "High Warlord Naj'entus", 22887 },
		{ "Supremus", 22898 },
		{ "Shade of Akama", 22841 },
		{ "Teron Gorefiend", 22871 },
		{ "Gurtogg Bloodboil", 22948 },
		{ "Reliquary of the Lost", 22856 },
		{ "Mother Shahraz", 22947 },
		{ "The Illidari Council" },
		{ "Illidan Stormrage", 22917 },
		{ "Trash Mobs" },
		{ "Reputation Trinkets" },
		{ "BT Patterns/Plans" },
	}

	menu["CoTOldHillsbrad"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time" .. ": " .. "Old Hillsbrad Foothills",
		DisplayName = "Old Hillsbrad Foothills",
		Type = "BCDungeon",
		Map = "CoTOldHillsbrad",
		{ "Lieutenant Drake" },
		{ "Captain Skarloc" },
		{ "Epoch Hunter" },
		{ "Trash Mobs" },
	}

	menu["CoTBlackMorass"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time" .. ": " .. "The Black Morass",
		DisplayName = "The Black Morass",
		Type = "BCDungeon",
		Map = "CoTBlackMorass",
		{ "Chrono Lord Deja" },
		{ "Temporus" },
		{ "Aeonus" },
	}

	menu["CoTHyjal"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time" .. ": " .. "Hyjal Summit",
		DisplayName = "Hyjal Summit",
		Type = "BCRaid",
		Map = "CoTHyjal",
		{ "Rage Winterchill" },
		{ "Anetheron" },
		{ "Kaz'rogal" },
		{ "Azgalor" },
		{ "Archimonde" },
		{ "Chromius" },
		{ "Trash Mobs - Items" },
		{ "Crafting Recipe Drops Page 1" },
		{ "Crafting Recipe Drops Page 2" },
	}

	menu["CFRSlavePens"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir" .. ": " .. "The Slave Pens",
		DisplayName = "The Slave Pens",
		Type = "BCDungeon",
		Map = "CFRTheSlavePens",
		{ "Mennu the Betrayer" },
		{ "Rokmar the Crackler" },
		{ "Quagmirran" },
	}

	menu["CFRSteamvault"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir" .. ": " .. "The Steamvault",
		DisplayName = "The Steamvault",
		Type = "BCDungeon",
		Map = "CFRTheSteamvault",
		{ "Hydromancer Thespia" },
		{ "Mekgineer Steamrigger" },
		{ "Warlord Kalithresh" },
		{ "Trash Mobs" },
	}

	menu["CFRUnderbog"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir" .. ": " .. "The Underbog",
		DisplayName = "The Underbog",
		Type = "BCDungeon",
		Map = "CFRTheUnderbog",
		{ "Hungarfen" },
		{ "Ghaz'an" },
		{ "Swamplord Musel'ek" },
		{ "The Black Stalker" },
	}

	menu["CFRSerpentshrine"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir" .. ": " .. "Serpentshrine Cavern",
		DisplayName = "Serpentshrine Cavern",
		Type = "BCRaid",
		Map = "CFRSerpentshrineCavern",
		{ "Hydross the Unstable" },
		{ "The Lurker Below" },
		{ "Leotheras the Blind" },
		{ "Fathom-Lord Karathress" },
		{ "Morogrim Tidewalker" },
		{ "Lady Vashj" },
		{ "Trash Mobs" },
	}

	menu["GruulsLair"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Gruul's Lair",
		Type = "BCRaid",
		Map = "GruulsLair",
		{ "High King Maulgar" },
		{ "Gruul the Dragonkiller" },
	}

	menu["HCRamparts"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel" .. ": " .. "Hellfire Ramparts",
		DisplayName = "Hellfire Ramparts",
		Type = "BCDungeon",
		Map = "HCHellfireRamparts",
		{ "Watchkeeper Gargolmar" },
		{ "Omor the Unscarred" },
		{ "Vazruden" },
	}

	menu["HCFurnace"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel" .. ": " .. "The Blood Furnace",
		DisplayName = "The Blood Furnace",
		Type = "BCDungeon",
		Map = "HCBloodFurnace",
		{ "The Maker" },
		{ "Broggok" },
		{ "Keli'dan the Breaker" },
	}

	menu["HCShatteredHalls"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel" .. ": " .. "The Shattered Halls",
		DisplayName = "The Shattered Halls",
		Type = "BCDungeon",
		Map = "HCTheShatteredHalls",
		{ "Grand Warlock Nethekurse" },
		{ "Blood Guard Porung" },
		{ "Warbringer O'mrogg" },
		{ "Warchief Kargath Bladefist" },
		{ "Trash Mobs" },
	}

	menu["HCMagtheridon"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel" .. ": " .. "Magtheridon's Lair",
		DisplayName = "Magtheridon's Lair",
		Type = "BCRaid",
		Map = "HCMagtheridonsLair",
		{ "Magtheridon" },
	}

	menu["Karazhan"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Karazhan",
		Type = "BCRaid",
		Map = "Karazhan",
		Loadfirst = 1,
		--{ "Servant's Quarter Animal Bosses" },
		{ "Attumen the Huntsman", 16152 },
		{ "Moroes", 15687 },
		{ "Maiden of Virtue", 16457 },
		--{ "Opera Event" },
		{ "Nightbane", 17225 },
		{ "The Curator", 15691 },
		{ "Terestian Illhoof", 15688 },
		{ "Shade of Aran", 16524 },
		{ "Netherspite", 15689 },
		{ "Chess Event", 16816 },
		{ "Prince Malchezaar", 15690 },
		--{ "Trash Mobs" },
	}

	menu["MagistersTerrace"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Sunwell Isle" .. ": " .. "Magisters' Terrace",
		DisplayName = "Magisters' Terrace",
		Type = "BCDungeon",
		Map = "MagistersTerrace",
		{ "Selin Fireheart" },
		{ "Vexallus" },
		{ "Priestess Delrissa" },
		{ "Kael'thas Sunstrider" },
		{ "Trash Mobs" },
	}

	menu["TKArc"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep" .. ": " .. "The Arcatraz",
		DisplayName = "The Arcatraz",
		Type = "BCDungeon",
		Map = "TempestKeepArcatraz",
		{ "Zereketh the Unbound" },
		{ "Wrath-Scryer Soccothrates" },
		{ "Dalliah the Doomsayer" },
		{ "Harbinger Skyriss" },
		{ "Trash Mobs" },
	}

	menu["TKBot"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep" .. ": " .. "The Botanica",
		DisplayName = "The Botanica",
		Type = "BCDungeon",
		Map = "TempestKeepBotanica",
		{ "Commander Sarannis" },
		{ "High Botanist Freywinn" },
		{ "Thorngrin the Tender" },
		{ "Laj" },
		{ "Warp Splinter" },
	}

	menu["TKMech"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep" .. ": " .. "The Mechanar",
		DisplayName = "The Mechanar",
		Type = "BCDungeon",
		Map = "TempestKeepMechanar",
		{ "Cache of the Legion" },
		{ "Mechano-Lord Capacitus" },
		{ "Nethermancer Sepethrea" },
		{ "Pathaleon the Calculator" },
	}

	menu["TKEye"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep" .. ": " .. "The Eye",
		DisplayName = "The Eye",
		Type = "BCRaid",
		Map = "TempestKeepTheEye",
		{ "Al'ar" },
		{ "Void Reaver" },
		{ "High Astromancer Solarian" },
		{ "Kael'thas Sunstrider" },
		{ "Trash Mobs" },
		{ "Legendary Items for Kael'thas Fight" },
	}

	menu["SunwellPlateau"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Sunwell Isle" .. ": " .. "Sunwell Plateau",
		DisplayName = "Sunwell Plateau",
		Type = "BCRaid",
		Map = "SunwellPlateau",
		{ "Kalecgos" },
		{ "Brutallus" },
		{ "Felmyst" },
		{ "Grand Warlock Alythess" },
		{ "High Commander Arynyes <Shadowsword Captain>" },
		{ "M'uru" },
		{ "Kil'jaeden" },
		{ "Trash Mobs" },
		{ "Jewelcrafting" },
		{ "Patterns/Plans" },
}

end
