local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

AtlasLoot:AddNewMenus({
    ["Heirloom"] = {
		Name = "Heirloom",
		{ "Trinkets", {} },
		{ "Necks", {} },
		{ "Rings", {} },
		{ "Weapons", {} },
		{ "Might", {} },
		{ "Shadowcraft", {} },
		{ "Dreadmist", {} },
		{ "Herods", {} },
		{ "Elements", {} },
		{ "Valor", {} },
		{ "IronFeather", {} },
		{ "Pvp Shoulders", {} },
	},
	
	----------------------------
    --------- Classic ----------
    ----------------------------
    ["MarkOfTriumph"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Mark of Triumph Vendor",
        Type = "ClassicDungeonExt",
        WebID = {1414503,"npc"},
		{ "Mark of Triumph Vendor", {} },
	},

    ["DungeonSetsCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dungeon Sets",
        Type = "ClassicDungeonExt",
		{ "Wildheart Raiment", {} },
		{ "Beaststalker Armor", {} },
		{ "Magister's Regalia", {} },
		{ "Lightforge Armor", {} },
        { "Vestments of the Devout", {} },
		{ "Shadowcraft Armor", {} },
		{ "The Elements", {} },
		{ "Dreadmist Raiment", {} },
        { "Battlegear of Valor", {} },
        { "Lightborne", {} },
        { "Thornheart", {} },
        { "Currents", {} },
        { "Bravery", {} },
        { "Courage", {} },
        { "Necropile Raiment", {} },
        { "Cadaverous Garb", {} },
        { "Bloodmail Regalia", {} },
        { "Deathbone Guardian", {} },
	},

    ["DungeonSetsUpgradedCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Dungeon Sets Quest Upgrades",
        Type = "ClassicDungeonExt",
		{ "Feralheart Raiment", {} },
		{ "Beastmaster Armor", {} },
		{ "Sorcerer's Regalia", {} },
		{ "Soulforge Armor", {} },
        { "Vestments of the Virtuous", {} },
		{ "Darkmantle Armor", {} },
		{ "The Five Thunders", {} },
		{ "Deathmist Raiment", {} },
        { "Battlegear of Heroism", {} },
	},

    ["TONE"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 1",
        Type = "ClassicRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

    ["TTWO"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 2",
        Type = "ClassicRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
        --{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
	},

	["TTHREE"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 3",
        Type = "ClassicRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        --{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

    ["ClassicSets"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Classic Sets",
		{ "Defias Leather", {} },
		{ "Embrace of the Viper", {} },
		{ "Chain of the Scarlet Crusade", {} },
		{ "The Gladiator", {} },
        { "Ironweave Battlesuit", {} },
		{ "The Postmaster", {} },
		{ "Shard of the Gods", {} },
		{ "Spirit of Eskhandar", {} },
		{ "Spider's Kiss", {} },
		{ "Dal'Rend's Arms", {} },
		{ "Major Mojo Infusion", {} },
		{ "Overlord's Resolution", {} },
		{ "Primal Blessing", {} },
		{ "Prayer of the Primal", {} },
		{ "Zanzil's Concentration", {} },
		{ "The Twin Blades of Hakkari", {} },
	},

    ["ZGSets"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Zul'Gurub",
		Type = "ClassicRaid",
		{ "Haruspex's Garb", {} },
		{ "Predator's Armor", {} },
		{ "Illusionist's Attire", {} },
		{ "Freethinker's Armor", {} },
        { "Confessor's Raiment", {} },
		{ "Madcap's Outfit", {} },
		{ "Augur's Regalia", {} },
		{ "Demoniac's Threads", {} },
		{ "Vindicator's Battlegear", {} },
	},

    ["AQ20Sets"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "AQ20 Class Sets",
		Type = "ClassicRaid",
		{ "Symbols of Unending Life", {} },
		{ "Trappings of the Unseen Path", {} },
		{ "Trappings of Vaulted Secrets", {} },
		{ "Battlegear of Eternal Justice", {} },
        { "Finery of Infinite Wisdom", {} },
		{ "Emblems of Veiled Shadows", {} },
		{ "Gift of the Gathering Storm", {} },
		{ "Implements of Unspoken Names", {} },
		{ "Battlegear of Unyielding Strength", {} },
		{ "Keepsakes of Endless Machinations", {} },
		{ "Regalia of Roaring Earth", {} },
		{ "Relics of Ferocious Vigor", {} },
		{ "Laurels of the Faithful Zealot", {} },
		{ "Instruments of Masterful Technique", {} },
		{ "Decorations of Martial Prowess", {} },
		{ "TabTrophies of Unrivaled Rageards", {} },
		{ "Remnants of Expansive Research", {} },
	},

    ["T2.5"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "AQ40 Class Sets - Tier 2.5",
		Type = "ClassicRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        --{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        { LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

    ["WorldEpicsCLASSIC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "BoE World Epics",
        Type = "ClassicDungeonExt",
		{ "Level 30-39", {} },
		{ "Level 40-49", {} },
		{ "Level 50-60", {} },
	},

	["DS3"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Dungeon 3 Sets",
		Type = "BCDungeon",
		{ "Hallowed Raiment", {} },
		{ "Mana-Etched Regalia", {} },
		{ "Incanter's Regalia", {} },
		{ "Oblivion Raiment", {} },
		{ "Assassination Armor", {} },
		{ "Wastewalker Armor", {} },
		{ "Moonglade Raiment", {} },
		{ "Beast Lord Armor", {} },
		{ "Tidefury Raiment", {} },
		{ "Desolation Battlegear", {} },
		{ "Bold Armor", {} },
		{ "Righteous Armor", {} },
		{ "Doomplate Battlegear", {} },
		{ "Divine Armor", {} },
		{ "Armor of the Just", {} },
		{ "Sentinel's Armor", {} },
		{ "Raiment of the Tides", {} },
		{ "Verdant's Regalia", {} },
	},

	["TFOUR"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 4",
        Type = "BCRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

	["TFIVE"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 5",
        Type = "BCRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

	["TSIX"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Tier 6",
        Type = "BCRaid",
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		--{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Guardian", {} },
        { LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
        { LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
        { LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"] .. " - Elemental", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARLOCK"], {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Avoidance Tank", {} },
        { LOCALIZED_CLASS_NAMES_MALE["WARRIOR"] .. " - Dps", {} },
	},

	["TBCSets"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Burning Crusade Sets",
		{ "Latro's Flurry", {} },
		{ "The Twin Stars", {} },
		{ "The Fists of Fury", {} },
		{ "The Twin Blades of Azzinoth", {} },
	},

	["BadgeShatt"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Shattrath City",
		{ "Cloth", {} },
		{ "Leather", {} },
		{ "Mail", {} },
		{ "Plate", {} },
		{ "Back", {} },
		{ "Totem/Idol/Libram", {} },
		{ "Weapons", {} },
		{ "Accessories", {} },
		{ "Fire Resistance Gear", {} },
	},

	["BadgeSunwell"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Sunwell Isle",
		{ "Cloth", {} },
		{ "Leather", {} },
		{ "Mail", {} },
		{ "Plate", {} },
		{ "Weapons", {} },
		{ "Accessories", {} },

	},

	["SunmoteSunwell"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Yrma - Sunmote Vendor",
		Type = "BCRaid",
		{ "Sunmote Vendor", {} },
	},

	["HardModeArena"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hardmode arena",
		{ "Hardmode arena", {} },
	},

	["HardModeArena2"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hardmode arena2",
		{ "Hardmode arena2", {} },
	},

	["WorldEpicsTBC"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "BoE World Epics",
		Type = "BCDungeon",
		{ "BoE World Epics", {} },
	},

	["WorldRaresTBC"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "BoE World Rares",
		Type = "BCDungeon",
		{ "BoE World Rares", {} },
	},
})