local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

AtlasLoot:AddNewMenus({

	----------------------------
    --------- Classic ----------
    ----------------------------
    ["AVMisc"] = {
		Name = "Alterac Valley",
		{ "Misc. Rewards", {} },
		{ "Alliance", {} },
		{ "Horde", {} },
	},

    ["AB_A"] = {
		Name = "Arathi Basin - Alliance",
        WebID = {509,"faction"},
		{ "Misc. Rewards", {} },
		{ "Level 60 Rewards", {} },
		{ "Level 40-49 Rewards", {} },
		{ "Level 30-39 Rewards", {} },
		{ "Level 20-29 Rewards", {} },
        { "The Defiler's Intent", {} },
        { "The Defiler's Purpose", {} },
        { "The Defiler's Will", {} },
        { "The Defiler's Determination", {} },
        { "The Defiler's Fortitude", {} },
        { "The Defiler's Resolution", {} },
        { "The Defiler's Resolve", {} },
	},

    ["AB_H"] = {
		Name = "Arathi Basin - Horde",
        WebID = {510,"faction"},
		{ "Misc. Rewards", {} },
		{ "Level 60 Rewards", {} },
		{ "Level 40-49 Rewards", {} },
		{ "Level 30-39 Rewards", {} },
		{ "Level 20-29 Rewards", {} },
        { "The Highlander's Intent", {} },
        { "The Highlander's Purpose", {} },
        { "The Highlander's Will", {} },
        { "The Highlander's Determination", {} },
        { "The Highlander's Fortitude", {} },
        { "The Highlander's Resolution", {} },
        { "The Highlander's Resolve", {} },
	},

    ["WSG_A"] = {
		Name = "Warsong Gulch - Alliance",
        WebID = {890,"faction"},
		{ "Misc. Rewards", {} },
		{ "Accessories", {} },
		{ "Weapons", {} },
		{ "Armor", {} },
	},

    ["WSG_H"] = {
		Name = "Warsong Gulch - Horde",
        WebID = {890,"faction"},
		{ "Misc. Rewards", {} },
		{ "Accessories", {} },
		{ "Weapons", {} },
		{ "Armor", {} },
	},

    ["PVPDruid"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["DRUID"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
        { "Weapons", {} },
        { "Back", {} },
        { "Misc Armor", {} },
	},

    ["PVPHunter"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["HUNTER"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPPaladin"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["PALADIN"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPPriest"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["PRIEST"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPRogue"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["ROGUE"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPShaman"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["SHAMAN"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPWarlock"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["WARLOCK"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPWarrior"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["WARRIOR"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPMage"] = {
		Name = LOCALIZED_CLASS_NAMES_MALE["MAGE"],
		{ "Rare Set - Alliance", {} },
		{ "Superior Rare Set - Alliance", {} },
		{ "Epic Set - Alliance", {} },
		{ "Superior Epic Set - Alliance", {} },
		{ "Rare Set - Horde", {} },
        { "Superior Rare Set - Horde", {} },
        { "Epic Set - Horde", {} },
        { "Superior Epic Set - Horde", {} },
	},

    ["PVPWeapons60"] = {
		Name = "PvP Weapons - Level 60",
		{ "Grand Marshal's - Alliance", {} },
		{ "Lieutenant Commander's - Alliance", {} },
		{ "High Warlord's - Horde", {} },
		{ "Champion's - Horde", {} },
	},

    ["PvP60Accessories"] = {
		Name = "PvP Accessories - Level 60",
		{ "Alliance", {} },
		{ "Horde", {} },
	},

    ["PvP60Ench"] = {
		Name = "PvP Enchants",
		{ "PvP Enchants", {} },
	},

	----------------------------
    ----------- TBC ------------
    ----------------------------
	["PVPHellfire"] = {
		Name = "Hellfire Fortifications",
		{ "Hellfire Fortifications", {} },
	},

	["PVPHalaa"] = {
		Name = "Nagrand - Halaa",
		{ "Nagrand - Halaa", {} },
	},

	["PVPSpiritTowers"] = {
		Name = "PvP",
		{ "Terokkar Forest - Spirit Towers", {} },
	},

	["PVPTwinSpireRuins"] = {
		Name = "Twin Spire Ruins",
		{ "Zangarmarsh - Twin Spire Ruins", {} },
	},

	["PVP70RepGear"] = {
		Name = "Rep PVP Gear",
		{ "Cloth", {} },
		{ "Leather", {} },
		{ "Mail", {} },
		{ "Plate", {} },
		{ "Cloth - Alliance", {} },
		{ "Leather - Alliance", {} },
		{ "Mail - Alliance", {} },
		{ "Plate - Alliance", {} },
		{ "Cloth - Horde", {} },
		{ "Leather - Horde", {} },
		{ "Mail - Horde", {} },
		{ "Plate - Horde", {} },
	},

	["PvP70HonorVendor"] = {
		Name = "Honor Vendor",
		{ "PvP Accessories", {} },
	},

	["Pvp70Season1"] = {
		Name = "Arena Season 1",
		WebID = {41015, "npc"},
		{ "Accessories", {} },
		{ "Gems & Enchants", {} },
		{ "Physical Damage - Weapons", {} },
		{ "Caster - Weapons", {} },
		{ "Cloth - Offset", {} },
		{ "Leather - Offset", {} },
		{ "Mail - Offset", {} },
		{ "Plate - Offset", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Demonology", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Destruction", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Elemental", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
	},

	["Pvp70Season2"] = {
		Name = "Arena Season 2",
		WebID = {41025, "npc"},
		{ "Back", {} },
		{ "Rings", {} },
		{ "Neck", {} },
		{ "Gems & Enchants", {} },
		{ "Physical Damage - Weapons", {} },
		{ "Caster - Weapons", {} },
		{ "Cloth - Offset", {} },
		{ "Leather - Offset", {} },
		{ "Mail - Offset", {} },
		{ "Plate - Offset", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Demonology", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Destruction", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Elemental", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
	},

	["Pvp70Season3"] = {
		Name = "Arena Season 3",
		WebID = {41035, "npc"},
		{ "Accessories", {} },
		{ "Physical Damage - Weapons", {} },
		{ "Caster - Weapons", {} },
		{ "Cloth - Offset", {} },
		{ "Leather - Offset", {} },
		{ "Mail - Offset", {} },
		{ "Plate - Offset", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Demonology", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Destruction", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Elemental", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
	},

	["Pvp70Season4"] = {
		Name = "Arena Season 4",
		WebID = {41045, "npc"},
		{ "Back", {} },
		{ "Rings", {} },
		{ "Neck", {} },
		{ "Trinket", {} },
		{ "Gems & Enchants", {} },
		{ "Physical Damage - Weapons", {} },
		{ "Caster - Weapons", {} },
		{ "Cloth - Offset", {} },
		{ "Leather - Offset", {} },
		{ "Mail - Offset", {} },
		{ "Plate - Offset", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["HUNTER"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["MAGE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["ROGUE"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARRIOR"], {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Demonology", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["WARLOCK"].. " - Destruction", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Feral", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Balance", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["DRUID"] .. " - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Enhancement", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Elemental", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["SHAMAN"].." - Restoration", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Protection", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Retribution", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PALADIN"] .. " - Holy", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Shadow", {} },
		{ LOCALIZED_CLASS_NAMES_MALE["PRIEST"] .. " - Holy", {} },
	},
})