local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")

AtlasLoot:AddNewMenus({
	--TBC Instances
	["BCKeys"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "BCKeys",
		{ "BCKeys", {} },
	},

	["AuchCrypts"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun - Auchenai Crypts",
		DisplayName = "Auchenai Crypts",
		Type = "BCDungeon",
		Map = "AuchAuchenaiCrypts",
		{ "Shirrak the Dead Watcher", { 18371 } },
		{ "Exarch Maladaar", { 18373 } },
		{ "Avatar of the Martyred", {} },
	},

	["AuchManaTombs"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun - Mana-Tombs",
		DisplayName = "Mana-Tombs",
		Type = "BCDungeon",
		Map = "AuchManaTombs",
		{ "Pandemonius", { 40110 } },
		{ "Tavarok", { 40112 } },
		{ "Nexus-Prince Shaffar", { 40115 } },
		{ "Yor" .. " (" .. "Heroic" .. ")", { 22930 } },
	},

	["AuchSethekk"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun - Sethekk Halls",
		DisplayName = "Sethekk Halls",
		Type = "BCDungeon",
		Map = "AuchSethekkHalls",
		{ "Darkweaver Syth", { 40130 } },
		{ "Anzu" .. " (" .. "Heroic" .. ")", { 23035 } },
		{ "Talon King Ikiss", { 25006 } },
	},

	["AuchShadowLab"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Auchindoun - Shadow Labyrinth",
		DisplayName = "Shadow Labyrinth",
		Type = "BCDungeon",
		Map = "AuchShadowLabyrinth",
		{ "Ambassador Hellmaw", { 40140 } },
		{ "Blackheart the Inciter", { 40141 } },
		{ "Grandmaster Vorpil", { 40142 } },
		{ "Murmur", { 40143 } },
		{ "Trash Mobs", {} },
	},

	["BlackTemple"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Black Temple",
		Type = "BCRaid",
		Map = "BlackTemple",
		{ "High Warlord Naj'entus", { 22887 } },
		{ "Supremus", { 22898 } },
		{ "Shade of Akama", { 22841 } },
		{ "Teron Gorefiend", { 22871 } },
		{ "Gurtogg Bloodboil", { 22948 } },
		{ "Reliquary of the Lost", { 22856 } },
		{ "Mother Shahraz", { 22947 } },
		{ "The Illidari Council", {} },
		{ "Illidan Stormrage", { 22917 } },
		{ "Trash Mobs", {} },
		{ "Reputation Trinkets", {} },
		{ "BT Patterns/Plans", {} },
	},

	["CoTOldHillsbrad"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time - Old Hillsbrad Foothills",
		DisplayName = "Old Hillsbrad Foothills",
		Type = "BCDungeon",
		Map = "CoTOldHillsbrad",
		{ "Lieutenant Drake", {} },
		{ "Captain Skarloc", {} },
		{ "Epoch Hunter", {} },
		{ "Trash Mobs", {} },
	},

	["CoTBlackMorass"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time - The Black Morass",
		DisplayName = "The Black Morass",
		Type = "BCDungeon",
		Map = "CoTBlackMorass",
		{ "Chrono Lord Deja", {17879} },
		{ "Temporus", {17880} },
		{ "Aeonus", {17881} },
	},

	["CoTHyjal"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Caverns of Time - Hyjal Summit",
		DisplayName = "Hyjal Summit",
		Type = "BCRaid",
		Map = "CoTHyjal",
		{ "Rage Winterchill", {17767} },
		{ "Anetheron", {17808} },
		{ "Kaz'rogal", {17888} },
		{ "Azgalor", {17842} },
		{ "Archimonde", {17968} },
		{ "Chromius", {92179} },
		{ "Rep Rings", {} },
		{ "Trash Mobs - Items", {} },
		{ "Crafting Recipes", {} },
	},

	["CFRSlavePens"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir - The Slave Pens",
		DisplayName = "The Slave Pens",
		Type = "BCDungeon",
		Map = "CFRTheSlavePens",
		{ "Mennu the Betrayer", {17941, 2061629} },
		{ "Rokmar the Crackler", {17991} },
		{ "Quagmirran", {17942} },
	},

	["CFRSteamvault"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir - The Steamvault",
		DisplayName = "The Steamvault",
		Type = "BCDungeon",
		Map = "CFRTheSteamvault",
		{ "Hydromancer Thespia", {17797} },
		{ "Mekgineer Steamrigger", {17796} },
		{ "Warlord Kalithresh", {17798,2061802} },
		{ "Trash Mobs", {} },
	},

	["CFRUnderbog"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir - The Underbog",
		DisplayName = "The Underbog",
		Type = "BCDungeon",
		Map = "CFRTheUnderbog",
		{ "Hungarfen", {17770} },
		{ "Ghaz'an", {18105} },
		{ "Swamplord Musel'ek", {17826,2061716} },
		{ "The Black Stalker", {17882} },
	},

	["CFRSerpentshrine"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Coilfang Reservoir - Serpentshrine Cavern",
		DisplayName = "Serpentshrine Cavern",
		Type = "BCRaid",
		Map = "CFRSerpentshrineCavern",
		{ "Hydross the Unstable", {21216} },
		{ "The Lurker Below", {21217} },
		{ "Leotheras the Blind", {21215} },
		{ "Fathom-Lord Karathress", {21214} },
		{ "Morogrim Tidewalker", {21213} },
		{ "Lady Vashj", {21212} },
		{ "Trash Mobs", {} },
	},

	["GruulsLair"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Gruul's Lair",
		Type = "BCRaid",
		Map = "GruulsLair",
		{ "High King Maulgar", {18831} },
		{ "Gruul the Dragonkiller", {19044} },
	},

	["HCRamparts"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel - Hellfire Ramparts",
		DisplayName = "Hellfire Ramparts",
		Type = "BCDungeon",
		Map = "HCHellfireRamparts",
		{ "Watchkeeper Gargolmar", {17306} },
		{ "Omor the Unscarred", {17308} },
		{ "Vazruden", {} },
	},

	["HCFurnace"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel - The Blood Furnace",
		DisplayName = "The Blood Furnace",
		Type = "BCDungeon",
		Map = "HCBloodFurnace",
		{ "The Maker", {17381} },
		{ "Broggok", {17380} },
		{ "Keli'dan the Breaker", {17377} },
	},

	["HCShatteredHalls"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel - The Shattered Halls",
		DisplayName = "The Shattered Halls",
		Type = "BCDungeon",
		Map = "HCTheShatteredHalls",
		{ "Grand Warlock Nethekurse", {16807} },
		{ "Blood Guard Porung", {20923, 2061628} },
		{ "Warbringer O'mrogg", {16809, 2076150} },
		{ "Warchief Kargath Bladefist", {16808} },
		{ "Trash Mobs", {} },
	},

	["HCMagtheridon"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Hellfire Citadel - Magtheridon's Lair",
		DisplayName = "Magtheridon's Lair",
		Type = "BCRaid",
		Map = "HCMagtheridonsLair",
		{ "Magtheridon", { 17257 } },
	},

	["Karazhan"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Karazhan",
		Type = "BCRaid",
		Map = "Karazhan",
		Loadfirst = 3,
		{ "Charred Bone Fragment (Quest Item)", {} },
		{ "Servant's Quarter Animal Bosses", {} },
		{ "Attumen the Huntsman", { 16152 } },
		{ "Moroes", { 15687 } },
		{ "Keanna's Log (Quest Item)", {} },
		{ "Maiden of Virtue", { 16457 } },
		{ "Opera Event", {} },
		{ "Nightbane", { 17225 } },
		{ "The Curator", { 15691 } },
		{ "Terestian Illhoof", { 15688 } },
		{ "Shade of Aran", { 16524 } },
		{ "Netherspite", { 15689 } },
		{ "Chess Event", { 16816 } },
		{ "Prince Malchezaar", { 15690 } },
		{ "Trash Mobs", {} },
	},

	["MagistersTerrace"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Sunwell Isle - Magisters' Terrace",
		DisplayName = "Magisters' Terrace",
		Type = "BCDungeon",
		Map = "MagistersTerrace",
		{ "Selin Fireheart", {24723} },
		{ "Vexallus", {24744} },
		{ "Priestess Delrissa", {24560} },
		{ "Kael'thas Sunstrider", {24664} },
		{ "Trash Mobs", {} },
	},

	["TKArc"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep - The Arcatraz",
		DisplayName = "The Arcatraz",
		Type = "BCDungeon",
		Map = "TempestKeepArcatraz",
		{ "Zereketh the Unbound", {40080} },
		{ "Wrath-Scryer Soccothrates", {40081} },
		{ "Dalliah the Doomsayer", {40082,2076655} },
		{ "Harbinger Skyriss", {25004} },
		{ "Trash Mobs", {} },
	},

	["TKBot"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep - The Botanica",
		DisplayName = "The Botanica",
		Type = "BCDungeon",
		Map = "TempestKeepBotanica",
		{ "Commander Sarannis", {40070,2061739} },
		{ "High Botanist Freywinn", {40071,2060635} },
		{ "Thorngrin the Tender", {40072} },
		{ "Laj", {40073} },
		{ "Warp Splinter", {40074} },
	},

	["TKMech"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep - The Mechanar",
		DisplayName = "The Mechanar",
		Type = "BCDungeon",
		Map = "TempestKeepMechanar",
		{ "Cache of the Legion", {} },
		{ "Mechano-Lord Capacitus", {40060} },
		{ "Nethermancer Sepethrea", {40061,2060796} },
		{ "Pathaleon the Calculator", {40062, 2061806} },
	},

	["TKEye"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Tempest Keep - The Eye",
		DisplayName = "The Eye",
		Type = "BCRaid",
		Map = "TempestKeepTheEye",
		{ "Al'ar", {19514} },
		{ "Void Reaver", {19516} },
		{ "High Astromancer Solarian", {18805} },
		{ "Kael'thas Sunstrider", {19622} },
		{ "Trash Mobs", {} },
		{ "Legendary Items for Kael'thas Fight", {} },
	},

	["SunwellPlateau"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Sunwell Isle - Sunwell Plateau",
		DisplayName = "Sunwell Plateau",
		Type = "BCRaid",
		Map = "SunwellPlateau",
		{ "Kalecgos", {} },
		{ "Brutallus", {24882} },
		{ "Felmyst", {25038} },
		{ "Grand Warlock Alythess", {25166} },
		{ "High Commander Arynyes <Shadowsword Captain>", {25837} },
		{ "M'uru", {} },
		{ "Kil'jaeden", {25315} },
		{ "Trash Mobs", {} },
		{ "Jewelcrafting", {} },
		{ "Patterns/Plans", {} },
	},

	["ZulAman"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Zul'Aman",
		Type = "BCRaid",
		Map = "ZulAman",
		{ "Nalorakk", {23576} },
		{ "Akil'zon", {23574} },
		{ "Jan'alai", {23578} },
		{ "Halazzi", {23577} },
		{ "Hex Lord Malacrass", {24239} },
		{ "Zul'jin", {23863} },
		{ "Trash Mobs", {} },
		{ "Enchants", {} },
	},

	["WorldBossesTBC"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "World Bosses",
		Type = "BCRaid",
		{ "Doom Lord Kazzak", {} },
		{ "Doomwalker", {} },
	},

	["KarazhanCryptsTBC"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "The Karazhan Crypts",
		Type = "BCkarazhanCrypts",
		Index = 5,
		{ "Cynfael", {}, WebID = {254401,"npc"} },
		{ "Dryn Miel <The Second Eidolon>", {}, WebID = {254413,"npc"} },
		{ "Kurgoth Doomreaver", {}, WebID = {254406,"npc"} },
		{ "The Judgement of Sinners", {}, WebID = {254405,"npc"} },
		{ "Takan Velor <The Hero of Deadwind>", {}, WebID = {654564,"npc"} },
		{ "Captain Taveir (Rare Spawn)", {}, WebID = {254495,"npc"} },
		{ "Kelivex Autumnvale (Rare Spawn)", {}, WebID = {254493,"npc"} },
	},

	["BlackrockCavernsTBC"] = {
		Module = "AtlasLoot_BurningCrusade",
		Name = "Blackrock Caverns",
		Type = "BCDungeon",
		{ "Ascendant Lord Obsidius", {}, WebID = {39705,"npc"} },
		{ "Beauty", {}, WebID = {39700,"npc"} },
		{ "Corla, Herald of Twilight", {}, WebID = {39679,"npc"} },
		{ "Karsh Steelbender <Twilight Armorer>", {}, WebID = {39698,"npc"} },
		{ "Rom'ogg Bonecrusher", {}, WebID = {39665,"npc"} },
	},

	["FrozenReachTBC"] = {
		Module = "AtlasLoot_OriginalWoW",
		Name = "Frozen Reach",
		Type = "ManastormTBC",
		{ "Frozen Reach", {}, WebID = {1298888,"item"} },
	},
})
