local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot")
local AtlasLoot = LibStub("AceAddon-3.0"):GetAddon("AtlasLoot")
local collection = AtlasLoot.ui.menus.collection

collection.WorldEventsCLASSIC = {
	Module = "AtlasLootWorldEvents",
	{ "Seasonal", "BrewfestCLASSIC", "Header"},
	{ "", "BrewfestCLASSIC"},
	{ "", "DayoftheDead"},
	{ "", "HalloweenCLASSIC"},
	{ "", "Valentineday"},
	{ "", "MidsummerFestivalCLASSIC"},
	{ "", "PilgrimsBounty"},
	{ "", "ChildrensWeek"},
	{ "", "Winterviel"},
	{ "", "HarvestFestival"},
	{ "", "LunarFestival"},
	{ "", "Noblegarden"},
	{ "Other", "Darkmoon", "Header"},
	{ "", "Darkmoon"},
	{ "", "GurubashiArena"},
	{ "", "AbyssalCouncil"},
	{ "", "ElementalInvasion"},
	{ "", "ScourgeInvasionEvent"},
	{ "", "FishingExtravaganza"},
}

	collection.WorldEventsTBC = {
		Module = "AtlasLootWorldEvents",
		{ "Seasonal", "BrewfestTBC", "Header"},
		{ "", "BrewfestTBC"},
		{ "", "DayoftheDead"},
		{ "", "HalloweenTBC"},
		{ "", "Valentineday"},
		{ "", "MidsummerFestivalTBC"},
		{ "", "PilgrimsBounty"},
		{ "", "ChildrensWeek"},
		{ "", "Winterviel"},
		{ "", "HarvestFestival"},
		{ "", "LunarFestival"},
		{ "", "Noblegarden"},
		{ "Other", "BashirLanding", "Header"},
		{ "", "BashirLanding"},
		{ "", "GurubashiArena"},
		{ "", "Shartuul"},
		{ "", "AbyssalCouncil"},
		{ "", "Skettis"},
		{ "", "Darkmoon"},
		{ "", "FishingExtravaganza"},
		{ "", "EthereumPrison"},
	}

	collection.WorldEventsWRATH = {
		Module = "AtlasLootWorldEvents",
		{ "Seasonal", "BrewfestWRATH", "Header"},
		{ "", "BrewfestWRATH"},
		{ "", "DayoftheDead"},
		{ "", "HalloweenWRATH"},
		{ "", "Valentineday"},
		{ "", "MidsummerFestivalWRATH"},
		{ "", "PilgrimsBounty"},
		{ "", "ChildrensWeek"},
		{ "", "Winterviel"},
		{ "", "HarvestFestival"},
		{ "", "LunarFestival"},
		{ "", "Noblegarden"},
		{ "Other", "ArgentTournament", "Header"},
		{ "", "ArgentTournament"},
		{ "", "GurubashiArena"},
		{ "", "Shartuul"},
		{ "", "Skettis"},
		{ "", "Darkmoon"},
		{ "", "FishingExtravaganza"},
	}
